- name: enalbe epel-repo
  yum: 
    name: epel-release
    state: latest

- name: Start pythontask service
  shell: "systemctl start pythontask.service"
  become: yes

- name: Enable pythontask service
  shell: "systemctl enable pythontask.service"
  become: yes

- name: Start pythontask timer
  shell: "systemctl start pythontask.timer"
  become: yes
  notify: Restart pythontask

- name: Enable pythontask timer
  shell: "systemctl enable pythontask.timer"
  become: yes

